# Generated by Django 4.2.5 on 2023-10-21 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.BooleanField(default=False)),
                ('name', models.CharField()),
                ('phone', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_question', models.TextField()),
                ('text_answer', models.TextField()),
                ('point', models.FloatField()),
                ('is_multi_question', models.BooleanField()),
                ('is_media_content', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField()),
                ('number_tour', models.IntegerField()),
                ('description', models.TextField()),
                ('max_command', models.IntegerField()),
                ('total_result', models.FloatField()),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindclubapp.gametype')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_question', models.IntegerField()),
                ('result', models.FloatField()),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindclubapp.command')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindclubapp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Subquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_question', models.TextField()),
                ('text_answer', models.TextField()),
                ('point', models.FloatField()),
                ('is_media_content', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindclubapp.question')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindclubapp.gametype')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField()),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindclubapp.command')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindclubapp.question')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindclubapp.season'),
        ),
        migrations.AddField(
            model_name='question',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindclubapp.tour'),
        ),
        migrations.CreateModel(
            name='MultiContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_content', models.BinaryField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindclubapp.question')),
                ('subquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindclubapp.subquestion')),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='cap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindclubapp.player'),
        ),
        migrations.AddField(
            model_name='command',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindclubapp.quiz'),
        ),
    ]
